### ISSUE TITLE
Bob is adding builds for all Ubuntu LTS versions

### ISSUE THREAD

**Issue by ericmj** [LostKobrakai/hex-bobs-list#7]
https://github.com/hexpm/bob/pull/68

We have also deprecated the Alpine builds because it is not clear if they are being used. We will no longer build more Alpine images but the old images will remain.

**Comment by LostKobrakai** [comment]
Thanks for the headsup. I'll have a look at how to best present the versions then.

**Comment by LostKobrakai** [comment]
I've removed the alpine ones, no need to promote deprecated builds. Instead the ubuntu lts versions are now listed
